services:
  user_db:
    image: postgres:15
    container_name: user_db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: ${USER_DB_USER}
      POSTGRES_PASSWORD: ${USER_DB_PASSWORD}
      POSTGRES_DB: ${USER_DB_NAME}
    volumes:
      - user_postgres_data:/var/lib/postgresql/data

  dds:
    image: postgres:15
    container_name: dds
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: ${DDS_USER}
      POSTGRES_PASSWORD: ${DDS_PASSWORD}
      POSTGRES_DB: ${DDS_NAME}
    volumes:
      - dds_postgres_data:/var/lib/postgresql/data
      - ./manager_service_service/dds_init.sql:/docker-entrypoint-initdb.d/init.sql

  auth_service:
   build: ./authentication_service
   container_name: auth_service
   ports:
     - "8000:8000"
   depends_on:
     - user_db
   environment:
     POSTGRES_USER: ${USER_DB_USER}
     POSTGRES_PASSWORD: ${USER_DB_PASSWORD}
     POSTGRES_DB: ${USER_DB_NAME}
     POSTGRES_SERVER: user_db
     POSTGRES_PORT: 5432
     JWT_SECRET_KEY: ${JWT_SECRET_KEY}

  ui_service:
   build: ./ui_service # Adjust this to match your actual folder name
   container_name: ui_service
   depends_on:
     - auth_service
   environment:
     # Use the Docker internal DNS name to reach the backend
     BASE_URL: http://auth_service:8000/v1/users

  adminer:
    image: adminer
    restart: always
    ports:
      - "8081:8080"

  manager_worker:
    build: ./manager_worker
    container_name: manager_worker
    environment:
      MINIO_ENDPOINT: ${MINIO_ENDPOINT}
      MINIO_BUCKET: ${MINIO_BUCKET}
      MINIO_ACCESS_KEY: ${MINIO_ACCESS_KEY}
      MINIO_SECRET_KEY: ${MINIO_SECRET_KEY}

  manager_service:
    build: ./manager_service
    container_name: manager_service
    ports:
      - "8001:8000"
    depends_on:
      - dds
      - manager_worker
    environment:
      MANAGER_NAMESPACE: manager_service
      MANAGER_WORKER_IMAGE_NAME: manager_worker

      POSTGRES_DDS_USER: ${DDS_USER}
      POSTGRES_DDS_PASSWORD: ${DDS_PASSWORD}
      POSTGRES_DDS_DB: ${DDS_NAME}
      POSTGRES_DDS_SERVER: dds
      POSTGRES_DDS_PORT: 5432

      MINIO_ENDPOINT: ${MINIO_ENDPOINT}
      MINIO_BUCKET: ${MINIO_BUCKET}
      MINIO_ACCESS_KEY: ${MINIO_ACCESS_KEY}
      MINIO_SECRET_KEY: ${MINIO_SECRET_KEY}
    volumes:
      - ./manager_service:/app

volumes:
  user_postgres_data:
  dds_postgres_data: