apiVersion: v1
kind: Service
metadata:
  name: auth-service
  namespace: mapreduce
  labels:
    app: auth-service
spec:
  clusterIP: None
  selector:
    app: auth-service
  ports:
    - name: http
      port: 8000
      targetPort: 8000
