apiVersion: apps/v1
kind: Deployment
metadata:
  name: ui-service
  namespace: mapreduce
  labels:
    app: ui-service
spec:
  replicas: 3  # This handles the "high load" by running 3 copies
  selector:
    matchLabels:
      app: ui-service
  template:
    metadata:
      labels:
        app: ui-service
    spec:
      containers:
      - name: python-ui
        image: map-reduce-app-cli:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 8000
        env:
        - name: BASE_URL
          value: "http://auth-service.mapreduce.svc.cluster.local:8000/v1/users"
        - name: MANAGER_URL
          value: "http://manager-service.mapreduce.svc.cluster.local:8001/v1"
---
apiVersion: v1
kind: Service
metadata:
  name: ui-service-lb
  namespace: mapreduce
spec:
  type: NodePort
  selector:
    app: ui-service
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
      nodePort: 30000