apiVersion: v1
kind: ServiceAccount
metadata:
  name: manager-sa
  namespace: mapreduce
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: manager-role
  namespace: mapreduce
rules:
  - apiGroups: ["batch"]
    resources: ["jobs"]
    verbs: ["create", "get", "list", "watch", "delete", "patch"]

  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: manager-rolebinding
  namespace: mapreduce
subjects:
  - kind: ServiceAccount
    name: manager-sa
    namespace: mapreduce
roleRef:
  kind: Role
  name: manager-role
  apiGroup: rbac.authorization.k8s.io