apiVersion: v1
kind: Service
metadata:
  name: manager-service
  namespace: mapreduce
  labels:
    app: manager-service
spec:
  type: NodePort
  selector:
    app: manager-service
  ports:
    - name: http
      port: 8001
      targetPort: 8001
      nodePort: 30001